node {

    checkout scm

    env.DOCKER_API_VERSION="1.23"

    sh "git rev-parse --short HEAD > commit-id"

    tag = readFile('commit-id').replace("\n", "").replace("\r", "")
    appName = "puzzle"
    registryHost = "127.0.0.1:30400/"
    imageName = "${registryHost}${appName}:${tag}"
    env.BUILDIMG=imageName
    env.BUILD_TAG=tag

    stage "Build"

        sh "docker build -t ${imageName} -f applications/puzzle/Dockerfile applications/puzzle"

    stage "Push"

        sh "docker push ${imageName}"

    stage "Deploy"

       kubernetesDeploy configs: "applications/puzzle/k8s/deployment_custom.yaml", credentialsType: 'SSH', ssh: [sshCredentialsId: 'f3af67ad-7b97-424e-9466-ffb18247545a', sshServer: '192.168.1.73:6443']
//, kubeconfigId: 'kenzan_kubeconfig'
}
